### ISSUE TITLE
Inference on own LiDAR data

### ISSUE THREAD

**Issue by JorritWillaert** [pxiangwu/MotionNet#11]
Dear,

First of all would I like to thank you for the provided code. 
I understand how to preprocess and train the model, but I'm in the dark about how I could inference now on my own LiDAR data. We have a Velodyne ultra puck 32 LiDAR, as well as an Ouster OS1 & OS2, from which we can receive a bytestream. Are there certain parameters I can tweak in the model to accomodate for our LiDAR setup (we're not using 360°, the angle is tilted, ...).

Thanks in advance!

**Comment by pxiangwu** [comment]
Hi, for your own dataset, I think you can do the following two steps: (1) for a given frame at current timestamp, use the calibration information to align the past frames with the current one. (2) preprocess the point clouds into BEV maps, and feed these BEV maps into the network.

I think even if your LiDAR data is not 360°, the network can still predict as expected. This is because the final output will be masked by the occupancy information. That said, if a given grid cell is not occupied by some LiDAR points, the prediction at this cell will be thresholded to zero (i.e., background).

Similarly, it does not matter if the angle is tilted, as long as such a tilted angle is not very large. All you need to do is provide the BEV maps into the network.

**Comment by JorritWillaert** [comment]
Hi, 

Thank you very much for your reply! I will definitely try this out in the upcoming days.
