### ISSUE TITLE
Problems training train_single_seq

### ISSUE THREAD

**Issue by HenryJunW** [pxiangwu/MotionNet#4]
Impressive work. 

When I tried to train the model without using spatio-temporal consistency losses from scratch, I found out that the training dataset cannot be imported successfully. It turned out that there is a typo in the line 171 of  MotionNet/data/nuscenes_dataloader.py 'os.path.isfile(os.path.join(self.dataset_root, d))]', which is supposed to be 'os.path.isdir(os.path.join(self.dataset_root, d))]'. 

BTW, it would be very helpful if you can provide a pre-trained single-seq model. In addition, how long does it take to train the model?

**Comment by pxiangwu** [comment]
Hi, yes, that is a typo and should have been fixed in my original repo on Github instead of that on MERL (although my original repo was removed ...). And I also provide pre-trained models:

   - The pre-trained model for `train_multi_seq.py` can be downloaded from [Google Drive](https://drive.google.com/file/d/1i8M4Z8VPGv-prqL5NV4pTlqtsoNu1goG/view?usp=sharing) or [Dropbox](https://www.dropbox.com/s/7f5p02d6uwfajam/model.pth?dl=0)
   - The pre-trained model for `train_multi_seq_MGDA.py` can be downloaded from [Google Drive](https://drive.google.com/file/d/1LdJferXtyC3DYBEi6zWMIUTzUQFVq0o1/view?usp=sharing) or [Dropbox](https://www.dropbox.com/s/i6arwx2zt2dagyi/model_MGDA.pth?dl=0)

The training usually takes less than one day on a single RTX 2080 Ti GPU.

**Comment by HenryJunW** [comment]
Thanks for your instant response. Appreciate it.
